name: example
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  indent:
    path: ../

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0