name: indent
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  expected_output: ^1.2.2
  pedantic: ^1.8.0
  test: ^1.6.0
