name: indent
description: Change indentation in multiline Dart strings while preserving the existing relative indentation.
version: 2.0.0
homepage: https://github.com/roughike/indent

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  expected_output: ^2.0.0
  lint: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
